# Generated by Django 2.2.3 on 2019-07-01 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_creating', models.DateField(default=django.utils.timezone.now)),
                ('date_of_birth', models.DateField()),
                ('keyword', models.CharField(max_length=200)),
                ('book_revenue', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('review', models.CharField(max_length=500)),
                ('date_of_publication', models.DateField()),
                ('price', models.FloatField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('date_of_order', models.DateField(default=django.utils.timezone.now)),
                ('books_in_order', models.ManyToManyField(related_name='orders', to='library_app.Book')),
            ],
        ),
    ]
